package constants;

public class Diagnoses {
    public static String[] names = {
"Acinetobacter baumannii",
"Actinomyces israelii, Actinomyces gerencseriae and Propionibacterium propionicus",
"Alphavirus",
"Anaplasma phagocytophilum",
"Anaplasma species",
"Ancylostoma duodenale and Necator americanus",
"Angiostrongylus",
"Anisakis",
"Arcanobacterium haemolyticum",
"Ascaris lumbricoides",
"Aspergillus species",
"Astroviridae species",
"Babesia species",
"Bacillus anthracis",
"Bacillus cereus",
"Bacteroides species",
"Balantidium coli",
"Bartonella",
"Bartonella bacilliformis",
"Bartonella henselae",
"Batrachochytrium dendrabatidis",
"Baylisascaris species",
"BK virus",
"Blastocystis species",
"Blastomyces dermatitidis",
"Bordetella pertussis",
"Borrelia burgdorferi, Borrelia garinii, and Borrelia afzelii",
"Borrelia hermsii, Borrelia recurrentis, and other Borrelia species",
"Brucella species",
"Bunyaviridae species",
"Burkholderia mallei",
"Burkholderia pseudomallei",
"Caliciviridae species",
"Campylobacter species",
"Chlamydia trachomatis",
"Chlamydia trachomatis",
"Chlamydophila pneumoniae",
"Chlamydophila psittaci",
"Clonorchis sinensis",
"Clostridium botulinum; Note: Botulism is not an infection by Clostridium botulinum but caused by the intake of botulinum toxin.",
"Clostridium difficile",
"Clostridium perfringens",
"Clostridium tetani",
"Coccidioides immitis and Coccidioides posadasii",
"Coccidioides immitis or Coccidioides posadasii.",
"Colorado tick fever virus (CTFV)",
"Corynebacterium diphtheriae",
"Coxiella burnetii",
"Crimean-Congo hemorrhagic fever virus",
"Cryptococcus neoformans",
"Cryptosporidium species",
"Cyclospora cayetanensis",
"Cytomegalovirus",
"Dengue viruses (DEN-1, DEN-2, DEN-3 and DEN-4) – Flaviviruses",
"Dientamoeba fragilis",
"Diphyllobothrium",
"Dracunculus medinensis",
"Ebolavirus (EBOV)",
"Echinococcus species",
"Ehrlichia chaffeensis",
"Ehrlichia ewingii",
"Ehrlichia species",
"Entamoeba histolytica",
"Enterobius vermicularis",
"Enterococcus species",
"Enterovirus species",
"Enteroviruses, mainly Coxsackie A virus and enterovirus 71 (EV71)",
"Epstein–Barr virus (EBV)",
"Escherichia coli O157:H7, O111 and O104:H4",
"Fasciola hepatica and Fasciola gigantica",
"Fasciolopsis buski",
"Filarioidea superfamily",
"Francisella tularensis",
"Fusobacterium species",
"Geotrichum candidum",
"Giardia lamblia",
"Gnathostoma spinigerum and Gnathostoma hispidum",
"Green algae Desmodesmus armatus",
"Group A Streptococcus species",
"Guanarito virus",
"Haemophilus ducreyi",
"Haemophilus influenzae",
"Heartland virus",
"Helicobacter pylori",
"Hendra virus",
"Hepatitis A virus",
"Hepatitis B virus",
"Hepatitis C virus",
"Hepatitis D Virus",
"Hepatitis E virus",
"Herpes simplex virus 1 and 2 (HSV-1 and HSV-2)",
"Histoplasma capsulatum",
"HIV (Human immunodeficiency virus)",
"Human bocavirus (HBoV)",
"Human herpesvirus 6 (HHV-6) and human herpesvirus 7 (HHV-7)",
"Human metapneumovirus (hMPV)",
"Human parainfluenza viruses (HPIV)",
"Hymenolepis nana and Hymenolepis diminuta",
"Intestinal disease by Capillaria philippinensis, hepatic disease by Capillaria hepatica and pulmonary disease by Capillaria aerophila",
"Isospora belli",
"JC virus",
"Junin virus",
"Kingella kingae",
"Klebsiella granulomatis",
"Lassa virus",
"Legionella pneumophila",
"Legionella pneumophila",
"Leishmania species",
"Leptospira species",
"List of bacterial vaginosis microbiota",
"Listeria monocytogenes",
"Lymphocytic choriomeningitis virus (LCMV)",
"Machupo virus",
"Malassezia species",
"Marburg virus",
"Measles virus",
"Measles virus",
"Microsporidia phylum",
"Middle East respiratory syndrome coronavirus",
"Molluscum contagiosum virus (MCV)",
"Monkeypox virus",
"most commonly Chlamydia trachomatis and Neisseria gonorrhoeae",
"Mucorales order (Mucormycosis) and Entomophthorales order (Entomophthoramycosis)",
"multiple",
"multiple",
"multiple",
"multiple",
"multiple",
"multiple",
"multiple bacteria",
"multiple bacteria",
"multiple viruses",
"Mumps virus",
"Mycobacterium leprae and Mycobacterium lepromatosis",
"Mycobacterium ulcerans",
"Mycoplasma genitalium",
"Mycoplasma pneumoniae",
"Neisseria gonorrhoeae",
"Neisseria meningitidis",
"Nipah virus",
"Norovirus",
"numerous species of bacteria (Actinomycetoma) and fungi (Eumycetoma)",
"Onchocerca volvulus",
"One of the human papillomaviruses",
"Opisthorchis viverrini and Opisthorchis felineus",
"Orthomyxoviridae species",
"Paracoccidioides brasiliensis",
"parasitic dipterous fly larvae",
"Parvovirus B19",
"Pasteurella species",
"Pediculus humanus capitis",
"Pediculus humanus corporis",
"Piedraia hortae",
"Plasmodium species",
"Pneumocystis jirovecii",
"Poliovirus",
"Prevotella species",
"PRNP",
"PRNP",
"PRNP",
"PRNP",
"PRNP",
"Pthirus pubis",
"Rabies virus",
"Respiratory syncytial virus (RSV)",
"Rhinosporidium seeberi",
"Rhinovirus",
"Rickettsia",
"Rickettsia akari",
"Rickettsia prowazekii",
"Rickettsia rickettsii",
"Rickettsia species",
"Rickettsia typhi",
"Rift Valley fever virus",
"Rotavirus",
"Rubella virus",
"Sabiá virus",
"Salmonella enterica subsp. enterica, serovar typhi",
"Salmonella species",
"Sarcoptes scabiei",
"SARS coronavirus",
"Schistosoma species",
"Shigella species",
"Sin Nombre virus",
"Sporothrix schenckii",
"Staphylococcus species",
"Staphylococcus species",
"Streptococcus agalactiae",
"Streptococcus pneumoniae",
"Streptococcus pyogenes",
"Strongyloides stercoralis",
"Taenia solium",
"Taenia species",
"Toxocara canis or Toxocara cati",
"Toxocara canis or Toxocara cati",
"Toxoplasma gondii",
"Treponema pallidum",
"Trichinella spiralis",
"Trichomonas vaginalis",
"Trichophyton rubrum",
"Trichosporon beigelii",
"Trichuris trichiura",
"Trypanosoma brucei",
"Trypanosoma cruzi",
"unknown; evidence supports that it is infectious",
"Ureaplasma urealyticum",
"usually Ancylostoma braziliense; multiple other parasites",
"usually Burkholderia cepacia and other Burkholderia species",
"usually Candida albicans and other Candida species",
"usually Clostridium perfringens; other Clostridium species",
"usually Epidermophyton floccosum, Trichophyton rubrum, and Trichophyton mentagrophytes",
"usually Fonsecaea pedrosoi",
"usually Group A Streptococcus and Staphylococcus",
"usually Hortaea werneckii",
"usually Metagonimus yokagawai",
"usually Mycobacterium tuberculosis",
"usually Naegleria fowleri",
"usually Nocardia asteroides and other Nocardia species",
"usually Paragonimus westermani and other Paragonimus species",
"usually rhinoviruses and coronaviruses",
"usually Trichophyton species",
"usually Trichophyton species",
"usually Trichophyton species",
"usually Trichophyton species",
"usually Trichophyton tonsurans",
"Varicella zoster virus (VZV)",
"Varicella zoster virus (VZV)",
"Variola major or Variola minor",
"Venezuelan equine encephalitis virus",
"Vibrio cholerae",
"Vibrio parahaemolyticus",
"Vibrio vulnificus",
"West Nile virus",
"Wuchereria bancrofti and Brugia malayi",
"Yellow fever virus",
"Yersinia enterocolitica",
"Yersinia pestis",
"Yersinia pestis",
"Yersinia pseudotuberculosis",
"Zeaspora fungus",
"Zika virus"};
}
